//import {  } from "../services/masterServices/master.services";

export const apiMessage = {
    somethingWentWrong: 'something Went Wrong',
    checkMobileNumberExist: `Mobile number does not exist.`,
    checkMobileNumber: 'Mobile number exist.',
    validMobileNumber: 'Enter valid Mobile Number',
    emailAlreadyExist: 'Email Id Already Exists.',
    invalidCode: 'Invalid referral code.',
    mobileNumber: 'Mobile number already in use.',
    userCreated: 'User created successfully.',
    noDataFound: 'No data available.',
    stateList: 'List of states.',
    contryList: 'List of contry.',
    dataNotAvailable: 'Data is not available.',
    cityList: 'List of cities.',
    categoryList: 'List of categories.',
    wrongUpload: 'Wrong file extension, you can only upload pdf,doc,docx,png,jpg,jpeg.',
    fileUpload: 'File upload successfully.',
    update: 'Updated successfully.',
    emailNotExist: 'Email does not exit.',
    getEnum: 'Get enum list.',
    wrongEnumType: 'Wrong enum type.',
    checkLogin: 'Email or Password is invalid.',
    login: 'You have logged in successfully.',
    passwordChange: 'Password changed successfully.',
    filerDelete: 'File deleted successfully.',
    getPattern: 'Pattern list shown below.',
    getRemark: 'List of remarks.',
    checkUserId: 'Please Enter Check User Id',
    docDetails: 'Document Details',
    userId: 'Please Enter valid User Id.',
    bikeId: 'Please Enter valid Bike Id.',
    emailExist: 'Email Already Exist.',
    checkProductId: 'Check ProductId.',
    checkPublishedStatusEnumId: 'Check PublishedStatusEnumId.',
    userMembership: 'User Association Membership Added Successfully',
    getUserForTable: 'User list shown below.',
    mail: 'mail Info Added and mail send Successfully ',
    notMail: 'mail Info  not Added ',
    success: 'Success',
    error: 'Error',
    recordNotFound: 'No Data Found.',
    validZone: 'Enter Valid Zone.',
    addZoneDetails: 'Zone Details Added Successfully.',
    updateZoneDetails: 'Zone Details Update Successfully.',
    zoneAlreadyExist: 'Zone Name Already Exists.',

    addDeviceDetails: 'Device Details Added Successfully.',

    deviceLocked: 'Device Locked Successfully.',
    deviceUlLocked: 'Device unlocked Successfully.',
    deviceIsNotRegister: 'Device Is Not Registered.Please Registered First',
    //  updateZoneDetails: 'Zone Details Update Successfully.',

    addVehicleDetails: 'Vehicle Model Details Added Successfully.',
    updateVehicleDetails: 'Vehicle Model Details Update Successfully.',
    VehicleAlreadyExist: 'Vehicle Details Already Exists.',

    validDate: 'Enter Valid Date.',
    validVehicle: 'Enter Valid Vehicle Model.',
    validUid: 'Enter Valid Uid',
    checkUiD: 'UId Is Already Associated With Other Model.',
    addBikeInward: 'Bike Inward Details Added Successfully.',
    updateBikeInward: 'Bike Inward Details Update Successfully.',

    validLockNumber: 'Enter Valid Lock Number.',
    qrNumber : 'Enter Valid qrNumber.',
    validLockIMEINumber: 'Enter Valid Lock IMEI Number.',
    checkLockNumber: 'Lock Number Is Already Associated.',
    checkIMEiNumber: 'IMEI Number Is Already Associated.',
    uidAssociated: 'uid Is Already Associated.',
    checkLockIMEINumber: 'Lock Imei Number Is Already Associated With Other Lock.',
    addLockInward: 'Lock Inward Details Added Successfully.',
    updateLockInward: 'Lock Inward Details Update Successfully.',

    addBikeProduce: 'Bike Produce Successfully.',
    updateBikeProduce: 'Bike Produce Details Update Successfully.',
    statusUpdate: 'Bike Allotment Status Updated.',

    addBikeAllotment: 'Bike Allotment Successfully.',
    updateBikeAllotment: 'Bike Allotment Details Update Successfully.',

    InwardStatusUpdate: 'Inward Status Update Successfully',
    validDeviceId: 'Provide Valid Device Id',
    validLockStatus: 'Provide Valid Lock status for device lock. 1 for unlock or 2 for lock.',
    deviceNameExist: 'Device Name Already Exist In System.',
    
    imeiNotExist: 'Lock number and IMEI number are not matched in system.',
    deleteDevice: 'Device Delete Successfully.',
    deviceNameNotExist: 'Device Not Exist In System.',
    deviceIdAndIns: 'Device Id And Instruction Set Successfully.',
    validInformation: 'Device Information Is Not Valid',
    validZoneSize: 'Please Enter Valid Zone Size.',
    validCapacity: 'Please Enter Valid Capacity.',
    withdrawRequest: 'Request Created For Withdraw Amount From Your Wallet To Account.',
    processing: 'WithDraw Request Send For Processing.',
    completed: 'Withdraw Request Completed.',
  withdrawRequestCancelled: 'User Withdraw request is cancelled successfully.',
    addDeviceLog: 'Add Device.',
    instructionForLockDevice: 'Lock Device.',
    instructionForUnLockDevice: 'UnLock Device.',
    updateDeviceLockByDevice: 'Update Device Lock Status By Device.',
    deviceDeleted: 'Device Deleted.',
    1: 'UnLock',
    2: 'Lock',
    3: 'LockError',
    4: 'UnlockError',
    
   
    dIdNotNull:  'value is not available in request parameter.',
    addArea: 'Area Details Added Successfully.',
    updateArea: 'Area Details Updated Successfully.',
    addFarePlan: 'Fare Plan Details Added Successfully.',
    updateFarePlan: 'Fare Plan Details Updated Successfully.',
    paymentDone:'this transaction  amount has been  already added in your wallet',
    notPayment:'payment is not found.',
    PaymentFailed:'Payment Failed.',
    inwardDateValidation: 'Inward Date Can not Be greater than  current date.',
    bikeProduct:'please set bikeInwardId',
    lockInwardId: 'please set lockInwardId',
    checkLockIInwarddNotexit: 'This lockInwardId Is Not Exit.',
    checkLockIdNotexit: 'This lock Id Is Not Exit.',
    ccheckLockIMEINotexit: 'This lock IMEI Id Is Not Exit.',    
    ccheckLockIMEIAndLockNotexit: 'This lockId Is Not Matched With  lock IMEI Id.',
    ccheckInwardLockIMEIAndLockNotexit: 'This lockId  and IEMI Id Is Not Matched With inward  lockId and  IMEIId.',
    cannotUpdate: 'you can not edit this device is registered.',
    
    qrString : 'Please Set qrString Or lockNumber OR QRNumber',
    qrStringNot : 'can not set both qrString and lockNumber and QRNumber',
    cannotDelete: 'You Can Not Delete This Device Is Registered.',

    lockIdset: 'Please Set Lock Id.',
    lockNumberset: 'Please Set Lock Number.',
    autoActionType :'Please Set auto action type.',
    amount: 'Please Enter valid amount.',
    paymentTransactionsType: 'Please Enter valid paymentTransactionsType.',
    validTokane: 'Please Enter valid Token.',
    
    VaidAmount :'Please Enter Valid receivedAmount',
    notAdd:'Amount is not Add',
    clientUrlNotFound:'client Url Not Found',
    clientUrl: 'Please Enter valid client url.',
    validEnumStatusId: 'Enter Valid EnumStatusId.',
    validFromDateFormat: 'Enter Valid From Date Format.',
    validToDateFormat: 'Enter Valid To Date Format.',
    validMSg: 'Enter Valid ',
    fromDate: 'From Date',
    toDate: 'To Date',
    validToDate: 'Enter Valid To Date.',
    fromDateToDateCom: 'From Date Can Not Be Greater Than To Date.',
    unllAndUndefindeCheck: 'Can Not Be Null Or Undefined Values(UserId, BikeId, bikeRideingStatusEnumId).', 
    deviceIsNotExist: 'lock number does not exists',
    deviceSetId:'Please set device Id',
    userSetId:'Please set user Id',
    lockNotAvailable:'This Lock number is not available.',
    intractionsAlready:'This instruction already set.',
    dIdNotAvailable :'Please Set dId.',
    deviceNotRegistered : 'Device Is Not Registered.',

    mapCountryNotExsit: 'This Country name not exsit.',
    mapStateNotExsit: 'This State name not exsit.',
    mapCityNotExsit: 'This map city name not exsit.',
    userCityNotExsit: 'This user city name not exsit.',
    createdUser: 'Please Enter valid created user id.',
    orderNotFound:'Order Id Url Not Found',
         areaId:'Please Set Area areaId',
        AreaName:'Please Set Area Name',
        CountryName:'Please Set Area map Country Name',
        StateName:'Please Set Area map State Name',
        CityName:'Please Set Area map City Name',
        AreaNameExist:'This Area name already exists',
        planNotActive :'For this Day No Plan Activate.' ,
        bikeNotFound:'this bike is not found.',
        bikeBooked:'This Bike Is Already Booked By User.',
        userBikeBooked:'This Usr  Is Already Booked a Bike.',
        zoneId:'Please Set zone Id',
        bikeProduce:'Please produce bike for this lock number.',
        userCityName:'Please Set  user City Name',
        mapDrawObjectEnumId:'Please set mapDrawObjectEnumId',
        mapDrawObject:'Please set mapDrawObject',
        mapDrawObjectAddress:'Please set mapDrawObjectAddress',
        fullAddress:'Please set fullAddress',
        pinCode:'Please set pinCode',
        placeId:'Please set placeId',
        sw:'Please set value sw',
        ne:'Please set value ne',
        center : 'Please set value center',
        radius: 'Please set value radius',
        polygonpoint : 'Please set value polygonpoint',
        polygonpoint2 : 'Please set value polygonpoint2',

        mapCityId : 'Please set value mapCityId',
        actionSet : 'This action already set.',
        instructionNotSet: 'action is not completed because set instruction and request action are not matched ',
        sectionName:'Please Set Section Name',
        questions:'Please Set questions ',
        answer : 'Please Set Answer',
        faqPublishStatusEnumId : 'please set faqPublishStatusEnumId',
        addFAQ:'FAQ detail added successfully',
        editFAQ:'FAQ detail updated successfully',

        publishFAQ:'FAQ detail published successfully',
        unpublishFAQ:'FAQ detail unPublished successfully',

        bikeActive: 'bike Active successfully.',
        bikedeActive: 'bike deActive successfully.',

        addSetion:'Section detail added successfully',
        editSection:'Section detail updated successfully',

        lockunlockBybluetoot:'lock /unlock by bluetooth',
        powerOnOffBybluetoot : 'power on /off  Bluetooth',
        deveiceNotAvailable :'device is not available ',
        parameterMissing :'Some data/parameters are missing',
        LUCommandNotFound :'Lock/unlock command is not found/match',
        timeNotCorrect :'Timeout value is not correct',

       // CommandExecutionFailed:'Command Execution Failed such as id value is not correct or device id is not correct format only accept integer value and some other cases',
        APIKeyNotValid:'API Key is not valid for device id or something else',
        APIKeyNotPass:'API Key is not pass in header',
        LUCommondNotWork:'Lock /Unlock command are not work',
          commondDataNotAvailble:'commond data not found.' ,
        intervalTime:  'previous command is already in processing please wait for' ,
          ErrorInThirdpartyLockUnlockAPI :'Error In Third party Lock Unlock API',
          ErrorInThirdpartyPowerONOffAPI :'Error In Third party power On Off API',
          lockRequest : 'Your lock request is successfully completed.',
          unlockRequest : 'Your unlock request is successfully completed.',
          noDeveiceAvailable :'No device found.', 
          InvalidData :'Invalid data',
          CommandExecutionFailed :'lock/unlock execution failed.',
          Unauthorized :'Unauthorized.' ,
          powerOnRequest : 'Your power On request is successfully completed.',
          powerOffRequest : 'Your power Off request is successfully completed.',
          internalCallingTimeNotSet :'internal calling time is not set.' 
    
};
